<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpecialtyCategoriesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('specialty_categories')->truncate();

        $categories = [
            [
                'id' => 1,
                'slug' => 'acting',
                'name_fa' => 'بازیگری و اجرا',
                'parent_id' => null,
                'sort_order' => 1,
                'icon' => 'masks-theater',
                'is_active' => true,
            ],
            [
                'id' => 2,
                'slug' => 'stunt',
                'name_fa' => 'کاسکادوری و بدل',
                'parent_id' => null,
                'sort_order' => 2,
                'icon' => 'person-falling',
                'is_active' => true,
            ],
            [
                'id' => 3,
                'slug' => 'directing',
                'name_fa' => 'کارگردانی و دستیاری صحنه',
                'parent_id' => null,
                'sort_order' => 3,
                'icon' => 'clapperboard',
                'is_active' => true,
            ],
            [
                'id' => 4,
                'slug' => 'writing',
                'name_fa' => 'نویسندگی',
                'parent_id' => null,
                'sort_order' => 4,
                'icon' => 'pen-nib',
                'is_active' => true,
            ],
            [
                'id' => 5,
                'slug' => 'cinematography',
                'name_fa' => 'تصویربرداری',
                'parent_id' => null,
                'sort_order' => 5,
                'icon' => 'video',
                'is_active' => true,
            ],
            [
                'id' => 6,
                'slug' => 'lighting',
                'name_fa' => 'نورپردازی',
                'parent_id' => null,
                'sort_order' => 6,
                'icon' => 'lightbulb',
                'is_active' => true,
            ],
            [
                'id' => 7,
                'slug' => 'sound',
                'name_fa' => 'صدا',
                'parent_id' => null,
                'sort_order' => 7,
                'icon' => 'microphone',
                'is_active' => true,
            ],
            [
                'id' => 8,
                'slug' => 'music',
                'name_fa' => 'موسیقی',
                'parent_id' => null,
                'sort_order' => 8,
                'icon' => 'music',
                'is_active' => true,
            ],
            [
                'id' => 9,
                'slug' => 'editing',
                'name_fa' => 'تدوین و پساتولید',
                'parent_id' => null,
                'sort_order' => 9,
                'icon' => 'film',
                'is_active' => true,
            ],
            [
                'id' => 10,
                'slug' => 'vfx',
                'name_fa' => 'جلوه‌های ویژه و CGI',
                'parent_id' => null,
                'sort_order' => 10,
                'icon' => 'wand-magic-sparkles',
                'is_active' => true,
            ],
            [
                'id' => 11,
                'slug' => 'production-design',
                'name_fa' => 'طراحی صحنه',
                'parent_id' => null,
                'sort_order' => 11,
                'icon' => 'house',
                'is_active' => true,
            ],
            [
                'id' => 12,
                'slug' => 'costume',
                'name_fa' => 'طراحی لباس',
                'parent_id' => null,
                'sort_order' => 12,
                'icon' => 'shirt',
                'is_active' => true,
            ],
            [
                'id' => 13,
                'slug' => 'makeup',
                'name_fa' => 'گریم',
                'parent_id' => null,
                'sort_order' => 13,
                'icon' => 'paintbrush',
                'is_active' => true,
            ],
            [
                'id' => 14,
                'slug' => 'photography',
                'name_fa' => 'عکاسی',
                'parent_id' => null,
                'sort_order' => 14,
                'icon' => 'camera',
                'is_active' => true,
            ],
            [
                'id' => 15,
                'slug' => 'production-management',
                'name_fa' => 'تهیه و مدیریت تولید',
                'parent_id' => null,
                'sort_order' => 15,
                'icon' => 'briefcase',
                'is_active' => true,
            ],
            [
                'id' => 16,
                'slug' => 'casting',
                'name_fa' => 'کستینگ',
                'parent_id' => null,
                'sort_order' => 16,
                'icon' => 'users',
                'is_active' => true,
            ],
            [
                'id' => 17,
                'slug' => 'pr-marketing',
                'name_fa' => 'روابط عمومی و بازاریابی',
                'parent_id' => null,
                'sort_order' => 17,
                'icon' => 'bullhorn',
                'is_active' => true,
            ],
            [
                'id' => 18,
                'slug' => 'animation',
                'name_fa' => 'انیمیشن',
                'parent_id' => null,
                'sort_order' => 18,
                'icon' => 'dragon',
                'is_active' => true,
            ],
            [
                'id' => 19,
                'slug' => 'games',
                'name_fa' => 'بازی‌های ویدیویی',
                'parent_id' => null,
                'sort_order' => 19,
                'icon' => 'gamepad',
                'is_active' => true,
            ],
            [
                'id' => 20,
                'slug' => 'crew',
                'name_fa' => 'عوامل صحنه و پشت‌صحنه',
                'parent_id' => null,
                'sort_order' => 20,
                'icon' => 'people-carry-box',
                'is_active' => true,
            ],
            [
                'id' => 21,
                'slug' => 'coaching',
                'name_fa' => 'آموزش و مربیگری',
                'parent_id' => null,
                'sort_order' => 21,
                'icon' => 'chalkboard-user',
                'is_active' => true,
            ],
            [
                'id' => 22,
                'slug' => 'translation',
                'name_fa' => 'ترجمه و زیرنویس',
                'parent_id' => null,
                'sort_order' => 22,
                'icon' => 'language',
                'is_active' => true,
            ],
        ];

        DB::table('specialty_categories')->insert($categories);
    }
}
